[package]
name = "dotenvx_native"
version = "4.0.0"
edition = "2021"
rust-version = "1.83"
publish = false

[lib]
name = "dotenvx_native"
crate-type = ["cdylib"]

[dependencies]
dotenvx-primitives = "=2.1.2"
magnus = "0.8"
rb-sys = { version = "0.9.128", default-features = false, features = ["stable-api-compiled-fallback"] }
